---
title: 3D scene
hero_image: images/banner.png
description: Create a project with three-dimensional (3D) effects to add depth to
  your unique scene
version: 4
listed: false
copyedit: false
last_tested: '2020-09-14'
steps:
- title: Introduction
  completion: engaged
- title: Get inspiration
- title: Choose a theme
- title: Set the scene
- title: 3D effects
- title: Soundtrack
- title: User control
  completion: internal
- title: Add more
- title: Share
- title: Reflect
- title: What next?
