title: Moving within 3D environments
hero_image: images/banner.png
description: Create a 3D project -  relaxing, energising, funny, inspiring - to try and change someone’s mood using sprites that move within a backdrop
version: 4
listed: false
copyedit: false
last_tested: "2020-09-14"
steps:
  - title: Introduction
  - title: Get inspiration
  - title: Choose your theme
  - title: Scenery layers
  - title: Movement
  - title: Sound
  - title: Variable
  - title: Add more...
  - title: Share
  - title: Reflect
  - title: What next?
